version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9
    working_directory: ~/ci-test
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  compile:
    docker:
      - image: circleci/node:10.9
    steps:
      - checkout
      - run:
          name: app-build
          command: yarn add @angular/cli && yarn run build
  deploy:
    docker:
      - image: circleci/node:10.9
    steps:
      - checkout
      - run:
          name: app-deploy
          command: yarn run deploy
workflows:
  version: 2
  compile_and_test:
    jobs:
      - build
      - compile:
          requires:
            - build
      - deploy:
          requires:
            - build
            - compile
          filters:
            branches:
              only: master