version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9
    working_directory: ~/ci-test
    steps:
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - "node_modules"
  compile:
    docker:
      - image: circleci/node:10.9
    steps:
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn install
      - run:
          name: app-build
          command: yarn run build
      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - "node_modules"
  deploy:
    docker:
      - image: circleci/node:10.9
    steps:
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn install
      - run:
          name: app-deploy
          command: yarn run deploy
      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - "node_modules"
workflows:
  version: 2
  compile_and_test:
    jobs:
      - build
      - compile:
          requires:
            - build
      - deploy:
          requires:
            - build
            - compile
          filters:
            branches:
              only: master