version: 2

_reusable_commands:
  restore_npm_cache: &restore_npm_cache
    key: v1-dependencies-{{ checksum "package.json" }}
  install_npm_deps: &install_npm_deps
    name: install-dependencies
    command: yarn install
  save_npm_cache: &save_npm_cache
    key: v1-dependencies-{{ checksum "package.json" }}
    paths:
      - node_modules

jobs:
  build:
    docker:
      - image: circleci/node:10.9
    working_directory: /tmp
    steps:
      - checkout
      - restore_cache: *restore_npm_cache
      - run: *install_npm_deps
      - save_cache: *save_npm_cache
      - run:
          name: compile-app
          command: yarn run build
      - persist_to_workspace:
          root: workspace
          paths:
            - dist/ci-test
  deploy:
    docker:
      - image: circleci/node:10.9
    working_directory: /tmp
    - attach_workspace:
        at: /tmp/workspace
    steps:
      - checkout
      - restore_cache: *restore_npm_cache
      - run: *install_npm_deps
      - save_cache: *save_npm_cache
      - run:
          name: app-deploy
          command: yarn run deploy
workflows:
  version: 2
  compile_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master